POST http://127.0.0.1:1234/rpc/v0 HTTP/1.1
content-type: application/json

{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "Filecoin.WalletBalance",
    "params": ["t1krjaiug7pg52mcds7nw6rh6qftuik6gzmfvsuwq"]
}
